[build]
  publish = "dist"
  functions = "netlify/functions"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/ao"
  to = "/.netlify/functions/ao-bridge"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin/command"
  to = "/.netlify/functions/admin-command"
  status = 200
  force = true

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
